# Generated by Django 4.1.7 on 2023-04-02 07:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("OnlineStore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="quantity",
            field=models.IntegerField(max_length=20),
        ),
        migrations.CreateModel(
            name="groceryList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Vegetable_name",
                    models.CharField(max_length=100, verbose_name="Shopping list name"),
                ),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2023, 4, 2, 10, 40, 15, 738515)
                    ),
                ),
                ("is_organic", models.BooleanField(default=False)),
                ("quantity", models.IntegerField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
