<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-04-06 16:52
=======
# Generated by Django 4.1.7 on 2023-04-02 06:09
>>>>>>> 348082224675e5ab40635c41a7cc43d53a0e0cc4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("OnlineStore", "0001_initial"),
=======
        ('OnlineStore', '0001_initial'),
>>>>>>> 348082224675e5ab40635c41a7cc43d53a0e0cc4
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="store",
            name="quantity",
=======
            model_name='store',
            name='quantity',
>>>>>>> 348082224675e5ab40635c41a7cc43d53a0e0cc4
            field=models.IntegerField(max_length=20),
        ),
    ]
