# Generated by Django 4.1.7 on 2023-04-02 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OnlineStore", "0002_alter_store_quantity_grocerylist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grocerylist",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 2, 11, 28, 40, 591604)
            ),
        ),
    ]
