# Generated by Django 4.1.7 on 2023-04-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OnlineStore", "0002_alter_store_quantity"),
        ("OnlineStore", "0003_alter_grocerylist_created_at"),
    ]

    operations = []
