# Generated by Django 4.1.7 on 2023-04-15 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OnlineStore", "0004_merge_20230415_1325"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grocerylist",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 15, 13, 29, 17, 979449)
            ),
        ),
    ]
