# Generated by Django 4.1.7 on 2023-04-16 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OnlineStore", "0005_alter_grocerylist_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="groceryItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Shopping list name"),
                ),
                ("is_organic", models.BooleanField(default=False)),
                ("quantity", models.IntegerField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="grocerylist",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 16, 9, 20, 6, 674029)
            ),
        ),
    ]
