# Generated by Django 4.1.7 on 2023-04-15 14:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("OnlineStore", "0005_alter_grocerylist_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grocerylist",
            name="Vegetable_name",
            field=models.CharField(
                max_length=100, verbose_name="Shopping list item name"
            ),
        ),
        migrations.AlterField(
            model_name="grocerylist",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 15, 17, 11, 9, 531524)
            ),
        ),
        migrations.CreateModel(
            name="RecipeList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Grocery list item name"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Shopping list item description",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "grocery_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OnlineStore.grocerylist",
                    ),
                ),
            ],
        ),
    ]
