<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-04-16 08:36
=======
# Generated by Django 4.1.7 on 2023-04-15 14:35
>>>>>>> c15f5164e3ebff596aadd9ec4df778d378b10fb9

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("OnlineStore", "0006_groceryitems_alter_grocerylist_created_at"),
=======
        ("OnlineStore", "0006_alter_grocerylist_vegetable_name_and_more"),
>>>>>>> c15f5164e3ebff596aadd9ec4df778d378b10fb9
    ]

    operations = [
        migrations.AlterField(
            model_name="grocerylist",
            name="created_at",
            field=models.DateField(
<<<<<<< HEAD
                default=datetime.datetime(2023, 4, 16, 11, 36, 21, 956968)
=======
                default=datetime.datetime(2023, 4, 15, 17, 35, 13, 346859)
>>>>>>> c15f5164e3ebff596aadd9ec4df778d378b10fb9
            ),
        ),
    ]
