# Generated by Django 4.1.7 on 2023-04-16 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OnlineStore", "0008_alter_grocerylist_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grocerylist",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 16, 10, 24, 52, 203310)
            ),
        ),
    ]
